

# , 981639, 1372372
cache_data = {
                '1123360': {'status': 'CLOSED',
                            'status_resolution': 'CLOSED_ERRATA',
                            'whiteboard': '',
                            'flags': {'sat-6.1.0': '+'},
                            'resolution': 'ERRATA', 'id': '1123360'},
                '1405428': {'status': 'CLOSED',
                            'status_resolution': 'CLOSED_DUPLICATE',
                            'whiteboard': '',
                            'flags': {'sat-6.3.0': '?', 'sat-6.2.z': '?'},
                            'resolution': 'DUPLICATE', 'id': '1405428'},
                '1402826': {'status': 'CLOSED',
                            'status_resolution': 'CLOSED_DUPLICATE',
                            'whiteboard': '',
                            'flags': {'sat-6.2.z': '?'},
                            'resolution': 'DUPLICATE',
                            'id': '1402826'},
                '1328925': {'status': 'CLOSED',
                            'status_resolution': 'CLOSED_ERRATA',
                            'whiteboard': '',
                            'flags': {'sat-6.2.0': '+'},
                            'resolution': 'ERRATA',
                            'id': '1328925'},
                '1333805': {'status': 'CLOSED',
                            'status_resolution': 'CLOSED_ERRATA',
                            'whiteboard': '',
                            'flags': {'sat-6.2.0': '+'},
                            'resolution': 'ERRATA',
                            'id': '1333805'},
                '1219610': {'status': 'CLOSED',
                            'status_resolution': 'CLOSED_WONTFIX',
                            'whiteboard': '',
                            'flags': {'sat-backlog': '+'},
                            'resolution': 'WONTFIX',
                            'id': '1219610'},
                '1461026': {'status': 'NEW',
                            'flags': {'sat-6.2.0': '+'},
                            'id': '1461026'},
                '9999999': {'status': 'VERIFIED',
                            'flags': {'sat-6.2.0': '+'},
                            'id': '9999999'},
                '1377676': {
                    'status': 'CLOSED',
                    'other_clones': {},
                    'duplicate_of': {
                        'status': 'CLOSED',
                        'other_clones': {},
                        'duplicate_of': {
                            'status': 'CLOSED',
                            'other_clones': {
                                '1426382': {
                                    'status': 'VERIFIED',
                                    'other_clones': {},
                                    'status_resolution': 'VERIFIED_',
                                    'target_milestone': 'GA',
                                    'whiteboard': '',
                                    'dupe_of': None,
                                    'flags': {'sat-6.3.0': '+'},
                                    'cf_clone_of': 1351464,
                                    'depends_on': [1351464],
                                    'clones': [],
                                    'resolution': '',
                                    'id': '1426382'
                                }
                            },
                            'duplicate_of': None,
                            'status_resolution': 'CLOSED_ERRATA',
                            'target_milestone': '6.2.9',
                            'dependent_on': None,
                            'whiteboard': '',
                            'dupe_of': None,
                            'flags': {'sat-6.2.z': '+'},
                            'cf_clone_of': None,
                            'depends_on': [],
                            'clones': [
                                {
                                    'status': 'VERIFIED',
                                    'other_clones': {},
                                    'status_resolution':
                                    'VERIFIED_',
                                    'target_milestone': 'GA',
                                    'whiteboard': '',
                                    'dupe_of': None,
                                    'flags': {'sat-6.3.0': '+'},
                                    'cf_clone_of': 1351464,
                                    'depends_on': [1351464],
                                    'clones': [],
                                    'resolution': '',
                                    'id': '1426382'
                                }
                            ],
                            'resolution': 'ERRATA',
                            'id': '1351464',
                            'clone_of': None
                        },
                        'status_resolution': 'CLOSED_DUPLICATE',
                        'target_milestone': 'Unspecified',
                        'dependent_on': None,
                        'whiteboard': '',
                        'dupe_of': 1351464,
                        'flags': {},
                        'cf_clone_of': None,
                        'depends_on': [],
                        'clones': [],
                        'resolution': 'DUPLICATE',
                        'id': '1376046',
                        'clone_of': None
                    },
                    'status_resolution': 'CLOSED_DUPLICATE',
                    'target_milestone': 'Unspecified',
                    'dependent_on': None,
                    'whiteboard': '',
                    'dupe_of': 1376046,
                    'flags': {'sat-6.3.0': '?'},
                    'cf_clone_of': None,
                    'depends_on': [],
                    'clones': [],
                    'resolution': 'DUPLICATE',
                    'id': '1377676',
                    'clone_of': None
                },
                '8888888': {
                    'status_resolution': 'CLOSED_DUPLICATE',
                    'resolution': 'DUPLICATE',
                    'status': 'CLOSED',
                    'dupe_of': 7777777,
                    'cf_dupe_of': 7777777,
                    'target_milestone': 'Unspecified',
                    'duplicate_of': {
                        'id': '7777777',
                        'status': 'ASSIGNED',
                        'flags': {'sat-6.2.z': '+'},
                        'target_milestone': '6.2.9',
                    },
                    'flags': {'sat-6.2.z': '+'}
                },
                '7777777': {
                    'id': '7777777',
                    'status': 'ASSIGNED',
                    'flags': {'sat-6.2.z': '+'},
                    'target_milestone': '6.2.9',
                },
                '5555555': {
                    'id': '5555555',
                    'status': 'CLOSED',
                    'resolution': 'NEXTRELEASE',
                    'status_resolution': 'CLOSED_NEXTRELEASE',
                    'flags': {'sat-6.3.0': '?'},
                    'target_milestone': 'Unspecified',
                },
                '4444444': {
                    'id': '4444444',
                    'status': 'CLOSED',
                    'resolution': 'NOTABUG',
                    'status_resolution': 'CLOSED_NOTABUG',
                    'flags': {'sat-6.3.0': '?'},
                    'target_milestone': 'Unspecified',
                },
                '3333333': {
                    'id': '3333333',
                    'status': 'CLOSED',
                    'resolution': 'WORKSFORME',
                    'status_resolution': 'CLOSED_WORKSFORME',
                    'flags': {'sat-6.3.0': '?'},
                    'target_milestone': 'Unspecified',
                },
                '2222222': {
                    'id': '2222222',
                    'status': 'CLOSED',
                    'resolution': 'ERRATA',
                    'status_resolution': 'CLOSED_ERRATA',
                    'flags': {'sat-6.2.z': '+'},
                    'target_milestone': '6.2.9',
                },


}
