

# , 981639, 1372372
cache_data = {'1123360': {'status': 'CLOSED',
                           'status_resolution': 'CLOSED_ERRATA',
                           'whiteboard': '',
                           'flags': {'sat-6.1.0': '+'},
                           'resolution': 'ERRATA', 'id': '1123360'},
               '1405428': {'status': 'CLOSED',
                           'status_resolution': 'CLOSED_DUPLICATE',
                           'whiteboard': '',
                           'flags': {'sat-6.3.0': '?', 'sat-6.2.z': '?'},
                           'resolution': 'DUPLICATE', 'id': '1405428'},
               '1402826': {'status': 'CLOSED',
                           'status_resolution': 'CLOSED_DUPLICATE',
                           'whiteboard': '',
                           'flags': {'sat-6.2.z': '?'},
                           'resolution': 'DUPLICATE',
                           'id': '1402826'},
               '1328925': {'status': 'CLOSED',
                           'status_resolution': 'CLOSED_ERRATA',
                           'whiteboard': '',
                           'flags': {'sat-6.2.0': '+'},
                           'resolution': 'ERRATA',
                           'id': '1328925'},
               '1333805': {'status': 'CLOSED',
                           'status_resolution': 'CLOSED_ERRATA',
                           'whiteboard': '',
                           'flags': {'sat-6.2.0': '+'},
                           'resolution': 'ERRATA',
                           'id': '1333805'},
               '1219610': {'status': 'CLOSED',
                           'status_resolution': 'CLOSED_WONTFIX',
                           'whiteboard': '',
                           'flags': {'sat-backlog': '+'},
                           'resolution': 'WONTFIX',
                           'id': '1219610'}
               }
